### ISSUE TITLE
fcntl-fcntlman rendering issue

### ISSUE THREAD

**Issue by DanielDewberry** [beejjorgensen/bgnet#21]
Dear Beej

First of all, thank you for an excellent networking resource. I turn to my physical copy of the book whenever I turn my hand to networking and have done for many years. 

An entry in the  first column of the table in [fcntl manpage](https://github.com/beejjorgensen/bgnet/blob/main/src/bgnet_part_0900_man.md#fcntl-fcntlman) section is not rendering correctly on the [online copy](https://beej.us/guide/bgnet/html/index-wide.html#fcntlman) I'm currently viewing.

I gather that:

`i[O_ASYNC macro]i]O_ASYNC`

should be 

`[i[O_ASYNC macro]i]O_ASYNC`

Best regards

Daniel

**Comment by beejjorgensen** [comment]
Thanks! Uploading a fix now...
