### ISSUE TITLE
Update brazilian translate

### ISSUE THREAD

**Issue by kassane** [beejjorgensen/bgnet#7]
A few months ago the user [cv8minix3](https://github.com/cv8minix3/Traducao_Guia_Beejs_Sockets_em_C_PTBR) was updating this translation to the most recent version. However, later his github account is no longer available along with the repositories (one of them was the translation).

Before this happened (luckily) I ended up saving and converting to pdf and deleting the original content, because he was translating the html file.

**Note:** I tried to convert it to html but I don't know if it would help.

Files:
[Beej Networking - cv8minix3[converted].tar.gz](https://github.com/beejjorgensen/bgnet/files/5372194/Beej.Networking.-.cv8minix3.converted.tar.gz)

Version: 3.1.2

**Comment by beejjorgensen** [comment]
Thanks! Added!
